// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrpqaivfxmcmwbphxqqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpycHFhaXZmeG1jbXdicGh4cXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTgyNjMsImV4cCI6MjA3MjEzNDI2M30.2X1R3HtyKcgtWi3kOCVcMLUIsu3C3Hz5hdo3xbA8pQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});